// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtww-gR5p0vQlRRb5p22aNs2_DoZGqWNg',
    appId: '1:273984987549:web:d22b13cbc453de877d4f74',
    messagingSenderId: '273984987549',
    projectId: 'moto-flutter',
    authDomain: 'moto-flutter.firebaseapp.com',
    storageBucket: 'moto-flutter.appspot.com',
    measurementId: 'G-GGS7P45PB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2rwKQ0nti8s96rVFPaOzmuVDBOiL_nHA',
    appId: '1:273984987549:android:b3e85fb698f658db7d4f74',
    messagingSenderId: '273984987549',
    projectId: 'moto-flutter',
    storageBucket: 'moto-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwGUYb72SNyAkl8DVLIlfLZ8ANEi_P8b4',
    appId: '1:273984987549:ios:5e2d76646f754f9c7d4f74',
    messagingSenderId: '273984987549',
    projectId: 'moto-flutter',
    storageBucket: 'moto-flutter.appspot.com',
    iosBundleId: 'com.example.userapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwGUYb72SNyAkl8DVLIlfLZ8ANEi_P8b4',
    appId: '1:273984987549:ios:77bb498dc165c3ba7d4f74',
    messagingSenderId: '273984987549',
    projectId: 'moto-flutter',
    storageBucket: 'moto-flutter.appspot.com',
    iosBundleId: 'com.example.userapp.RunnerTests',
  );
}
